import{i as h,S as y}from"./assets/vendor-9310f15c.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const d of n.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function a(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerpolicy&&(n.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?n.credentials="include":e.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function l(e){if(e.ep)return;e.ep=!0;const n=a(e);fetch(e.href,n)}})();document.addEventListener("DOMContentLoaded",function(){const u=document.getElementById("searchForm"),s=document.getElementById("searchInput"),a=document.getElementById("gallery"),l=document.getElementById("loader"),e="41927484-8453b2dd3e18520885b5ece2f",n="https://pixabay.com/api/";let d=1;u.addEventListener("submit",function(t){t.preventDefault();const i=s.value.trim();i!==""&&(l.style.display="block",a.innerHTML="",f(i,d).then(function(r){r.length===0?m("Sorry, there are no images matching your search query. Please try again!"):r.forEach(function(c){const o=p(c);a.appendChild(o)})}).catch(function(r){console.error("Error fetching images:",r),m("An error occurred while fetching images. Please try again later.")}).finally(function(){l.style.display="none"}))});function f(t,i){return new Promise(function(r,c){fetch(`${n}?key=${e}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&page=${i}&per_page=40`).then(o=>o.json()).then(o=>r(o.hits)).catch(o=>c(o))})}function m(t){h.error({title:"Error",message:t})}function p(t){const i=document.createElement("div");i.className="card";const r=document.createElement("a");r.href=t.webformatURL,r.setAttribute("data-lightbox","gallery"),r.setAttribute("data-title",t.tags);const c=document.createElement("img");c.src=t.largeImageURL,c.alt=t.tags,r.appendChild(c),i.appendChild(r);const o=document.createElement("div");return o.className="image-info",o.innerHTML=`
      <p>Likes: ${t.likes}</p>
      <p>Views: ${t.views}</p>
      <p>Comments: ${t.comments}</p>
      <p>Downloads: ${t.downloads}</p>
    `,i.appendChild(o),i}});document.addEventListener("DOMContentLoaded",function(){const u=document.getElementById("galleryContainer"),s=images.map(a=>`
      <a href="${a.src}">
        <img src="${a.thumb}" alt="${a.alt}" title="${a.title}">
      </a>
    `).join("");u.innerHTML=s,new y(".gallery a")});
//# sourceMappingURL=commonHelpers.js.map
